links:
- product: firefox
  results:
  - test: position-absolute-001.html
  - test: position-absolute-002.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1543267
- product: firefox
  results:
  - test: flex-minimum-width-flex-items-004.xht
  - test: flex-minimum-width-flex-items-006.xht
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1500492
- product: firefox
  results:
  - subtest: .flexbox 10
    test: negative-overflow.html
  - subtest: .flexbox 8
    test: negative-overflow.html
  - subtest: .flexbox 9
    test: negative-overflow.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1626561
