links:
- product: chrome
  results:
  - status: FAIL
    test: font-synthesis-01.html
  - status: FAIL
    test: font-synthesis-02.html
  - status: FAIL
    test: font-synthesis-03.html
  - status: FAIL
    test: font-synthesis-04.html
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=509989
