links:
- product: firefox
  results:
  - subtest: '@property rules in shadow trees should have no effect'
    test: at-property-shadow.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1634365
