links:
- product: firefox
  results:
  - subtest: .grid 5
    test: grid-container-margin-border-padding-scrollbar-001.html
  - subtest: .grid 8
    test: grid-container-margin-border-padding-scrollbar-001.html
  - subtest: .grid 16
    test: grid-container-margin-border-padding-scrollbar-001.html
  - subtest: .grid 11
    test: grid-container-margin-border-padding-scrollbar-001.html
  - subtest: .grid 10
    test: grid-container-margin-border-padding-scrollbar-001.html
  - subtest: .grid 13
    test: grid-container-margin-border-padding-scrollbar-001.html
  - subtest: .grid 15
    test: grid-container-margin-border-padding-scrollbar-001.html
  - subtest: .grid 14
    test: grid-container-margin-border-padding-scrollbar-001.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1634318
