links:
- product: chrome
  results:
  - status: MISSING
    test: aes_cbc.https.worker.html
  - status: MISSING
    test: aes_ctr.https.worker.html
  - status: MISSING
    test: aes_gcm.https.worker.html
  - status: MISSING
    test: test_aes_cbc.https.html
  - status: MISSING
    test: test_aes_ctr.https.html
  - status: MISSING
    test: test_aes_gcm.https.html
  - status: FAIL
    test: hkdf.https.any.html?1-1000
  - status: FAIL
    test: hkdf.https.any.html?1001-2000
  - status: FAIL
    test: hkdf.https.any.html?2001-3000
  - status: FAIL
    test: pbkdf2.https.any.html?1-1000
  - status: FAIL
    test: pbkdf2.https.any.html?1001-2000
  - status: FAIL
    test: pbkdf2.https.any.html?2001-3000
  - status: FAIL
    test: pbkdf2.https.any.html?3001-4000
  - status: FAIL
    test: pbkdf2.https.any.html?4001-5000
  - status: FAIL
    test: pbkdf2.https.any.html?5001-6000
  - status: FAIL
    test: successes_AES-CBC.https.any.html
  - status: FAIL
    test: successes_AES-CTR.https.any.html
  - status: FAIL
    test: successes_AES-GCM.https.any.html
  - status: FAIL
    test: successes_AES-KW.https.any.html
  - status: FAIL
    test: symmetric_importKey.https.worker.html
  - status: FAIL
    test: test_symmetric_importKey.https.html
  url: https://bugs.chromium.org/p/chromium/issues/detail?id=960916
