links:
- product: firefox
  results:
  - test: RTCPeerConnection-setRemoteDescription-tracks.https.html
  - test: RTCDTMFSender-ontonechange.https.html
  - test: RTCRtpTransceiver.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1550493
- product: firefox
  results:
  - test: RTCRtpReceiver-getSynchronizationSources.https.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1534466
