links:
- product: firefox
  results:
  - subtest: Anchor selection accounts for negative positioning.
    test: negative-layout-overflow.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1517287
