links:
- product: firefox
  results:
  - subtest: Do not expose in stats remote addresses that are not known to be already
      exposed to JS
    test: getStats-remote-candidate-address.html
  url: https://bugzilla.mozilla.org/show_bug.cgi?id=1547123
