links:
- product: chrome
  results:
  - status: MISSING
    subtest: Blob with type "image/gif;"
    test: Blob-constructor.html
  - status: MISSING
    subtest: Invalid contentType ("text/plain")
    test: Blob-slice.html
  url: https://github.com/web-platform-tests/results-collection/issues/661
